services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - my_network

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        networks:
            - my_network

networks:
    my_network:
